apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpp
  template:
    metadata:
      labels:
        app: cpp
    spec:
      containers:
        - name: cpp-container
          image: youseifhu/cpp-app:latest
